import { Club } from '~/types'

export const clubList: Array<Club> = [
  {
    url: '/other/cu-leadership-club',
    name: 'CU Leadership Club (CULC)',
    category: 'other',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/other%2Fcu-leadership-club%2Flogo1.png?alt=media',
  },
  {
    url: '/other/co-founder-trainee',
    name: 'Co-founder Trainee',
    category: 'other',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/other%2Fco-founder-trainee%2Flogo1.png?alt=media',
  },
  {
    url: '/other/cu-blood',
    name: 'โครงการเลือดชมพู (CU Blood)',
    category: 'other',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/other%2Fcu-blood%2Flogo1.png?alt=media',
  },
  {
    url: '/other/cu-mun',
    name: 'Chulalongkorn Model United Nations (ChulaMUN)',
    category: 'other',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/logo_placeholder.png?alt=media',
  },
  {
    url: '/other/charm-chula',
    name: 'องค์กรฌาร์ม (CHARM Chula)',
    category: 'other',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/other%2Fcharm-chula%2Flogo.png?alt=media',
  },
  {
    url: '/other/coach-by-champ',
    name: 'Coach by ChAMP',
    category: 'other',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/other%2Fcoach-by-champ%2Flogo2.png?alt=media',
  },
  {
    url: '/wichakarn/potential-club',
    name: 'ชมรมพัฒนาศักยภาพ (Potential Club) ',
    category: 'wichakarn',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/logo_placeholder.png?alt=media',
  },
  {
    url: '/wichakarn/cu-cathoric',
    name: 'ชมรมศาสนศึกษาแผนกคาทอลิก (CU Catholic)',
    category: 'wichakarn',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/logo_placeholder.png?alt=media',
  },
  {
    url: '/wichakarn/chulalongkorn-university-buddhist-society-cubs',
    name: 'ชมรมพุทธศาสตร์และประเพณี (CUBS)',
    category: 'wichakarn',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/wichakarn%2Fcubs%2Flogo.jpg?alt=media&token=ed344cc2-59c7-45cc-bc49-bec9fcde0af9',
  },
  {
    url: '/wichakarn/cu-pen-club',
    name: 'ชมรมวรรณศิลป์ (CU Pen Club)',
    category: 'wichakarn',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/wichakarn%2Fcu-pen-club%2Flogo.png?alt=media&token=4aecb6a7-6ee7-4d0e-8034-d0bb2886454f',
  },
  {
    url: '/wichakarn/eq-club',
    name: 'ชมรมพัฒนาความฉลาดทางอารมณ์ (EQ Club)',
    category: 'wichakarn',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/logo_placeholder.png?alt=media',
  },
  {
    url: '/wichakarn/cuigen',
    name: 'ฑูตเยาวชนนานาชาติและสันติภาพสากล (CUiGEN)',
    category: 'wichakarn',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/logo_placeholder.png?alt=media',
  },
  {
    url: '/wichakarn/ceo',
    name: 'Chulalongkorn Entrepreneur Organization (CEO)',
    category: 'wichakarn',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/wichakarn%2Fceo%2Flogo.png?alt=media&token=852b0772-e89a-43c3-9b8c-230eaa13c3ed',
  },
  {
    url: '/wichakarn/cu-gavel-club',
    name: 'CU Gavel Club',
    category: 'wichakarn',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/logo_placeholder.png?alt=media',
  },
  {
    url: '/pat/anurak-chula',
    name: 'ชมรมอนุรักษ์สภาพแวดล้อม (อนุรักษ์ จุฬาฯ) ',
    category: 'pat',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/pat%2Fanurak-chula%2Flogo1.png?alt=media',
  },
  {
    url: '/pat/lohit-club-chula',
    name: 'ชมรมบริการโลหิตและสังคมสงเคราะห์ในพระบรมราชินูปถัมภ์ (Lohit Club Chula)',
    category: 'pat',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/pat%2Flohit-club-chula%2FLOGO.png?alt=media',
  },
  {
    url: '/pat/hill-tribe-club',
    name: 'ชมรมค่ายอาสาพัฒนาชาวไทยภูเขา (HTC)',
    category: 'pat',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/pat%2Fhill-tribe-club%2Flogo1.png?alt=media',
  },
  {
    url: '/pat/slum-club',
    name: 'จุฬาฯสู่ชุมชน (Slum Club)',
    category: 'pat',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/pat%2Fslum-club%2Flogo.png?alt=media',
  },
  {
    url: '/pat/chula-volunteers-for-vulnerable-children-club',
    name: 'ชมรมอาสาพัฒนาเพื่อเด็กฯ (cvvc)',
    category: 'pat',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/pat%2Fcvvc%2Flogo.png?alt=media',
  },
  {
    url: '/pat/voluntary-club-of-the-student-union-chulalongkorn-university',
    name: 'ชมรมค่ายอาสาสมัครสโมสรนิสิตจุฬาลงกรณ์มหาวิทยาลัย (สจม) ',
    category: 'pat',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/pat%2Fvoluntary-club-of-the-student-union-chulalongkorn-university%2Flogo1.png?alt=media',
  },
  {
    url: '/pat/aiesec-in-chulalongkorn-university',
    name: 'ชมรมไอเซคฯ (AIESEC in CU)',
    category: 'pat',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/logo_placeholder.png?alt=media',
  },
  {
    url: '/silpvat/awutthai',
    name: 'ชมรมศิลปป้องกันตัวและอาวุธไทย (Chula Thai Martial Arts)',
    category: 'silpvat',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/silpvat%2Fawutthai%2Flogo1.jpg?alt=media',
  },
  {
    url: '/silpvat/cu-chorus',
    name: 'วงนักร้องประสานเสียง (CU Chorus)',
    category: 'silpvat',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/logo_placeholder.png?alt=media',
  },
  {
    url: '/silpvat/cu-band',
    name: 'ชมรมดนตรีสากล (CU Band)',
    category: 'silpvat',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/silpvat%2Fcu-band%2Flogo.png?alt=media',
  },
  {
    url: '/silpvat/cu-thai-classical-music-club',
    name: 'ชมรมดนตรีไทย ',
    category: 'silpvat',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/logo_placeholder.png?alt=media',
  },
  {
    url: '/silpvat/mvcu',
    name: 'ชมรมภาพยนตร์ (MVCU)',
    category: 'silpvat',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/logo_placeholder.png?alt=media',
  },
  {
    url: '/silpvat/cu-photo-club',
    name: 'ชมรมศิลปะการถ่ายภาพ (CU Photo Club)',
    category: 'silpvat',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/silpvat%2Fcu-photo-club%2Flogo2.png?alt=media',
  },
  {
    url: '/silpvat/isan-art-and-culture-club',
    name: 'ชมรมศิลปวัฒนธรรมอีสาน (Isan Art and Culture Club)',
    category: 'silpvat',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/silpvat%2Fisan-art-and-culture-club%2Flogo.jpeg?alt=media',
  },
  {
    url: '/silpvat/cu-southern-art-and-culture-club',
    name: 'ชมรมศิลปวัฒนธรรมปักษ์ใต้',
    category: 'silpvat',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/logo_placeholder.png?alt=media',
  },
  {
    url: '/silpvat/thai-classical-dance-and-drama-club-chulalongkorn-university',
    name: 'ชมรมนาฏศิลป์และการละครไทย',
    category: 'silpvat',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/silpvat%2Fthai-classical-dance-and-drama-club-chulalongkorn-university%2Flogo2.jpg?alt=media',
  },
  {
    url: '/silpvat/cudc',
    name: 'ชมรมเต้นแห่งจุฬาลงกรณ์มหาวิทยาลัย (CUDC)',
    category: 'silpvat',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/silpvat%2Fcudc%2FLogo.JPG?alt=media',
  },
  {
    url: '/silpvat/cu-northern-art-and-culture-club',
    name: 'ชมรมศิลปวัฒนธรรมล้านนา (ชมรมล้านนา จุฬาฯ) ',
    category: 'silpvat',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/logo_placeholder.png?alt=media',
  },
  {
    url: '/geela/chula-esports',
    name: 'ชมรมกีฬาอิเล็กทรอกนิกส์ (Chula Esports)',
    category: 'geela',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/geela%2Fchula-esports%2Flogo2.png?alt=media',
  },
  {
    url: '/geela/petanquechula',
    name: 'ชมรมกีฬาเปตอง',
    category: 'geela',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/geela%2Fpetanquechula%2Flogo1.JPG?alt=media',
  },
  {
    url: '/geela/cu-fencing-club',
    name: 'ชมรมฟันดาบสากล',
    category: 'geela',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/logo_placeholder.png?alt=media',
  },
  {
    url: '/geela/chulalongkorn-university-dancesport-club',
    name: ' ชมรมลีลาศ (CU Dancesport Club)',
    category: 'geela',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/geela%2Fchulalongkorn-university-dancesport-club%2Flogo1.jpg?alt=media',
  },
  {
    url: '/geela/chula-rowing-crew',
    name: 'ชมรมเรือใบและเรือพาย',
    category: 'geela',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/geela%2Fchula-rowing-crew%2Flogo.JPG?alt=media&token=c28b9285-9b65-40f6-a584-1aad31e10b24',
  },
  {
    url: '/geela/cu-judo-club',
    name: 'ชมรมยูโด(CU Judo Club)',
    category: 'geela',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/logo_placeholder.png?alt=media',
  },
  {
    url: '/geela/chula-shooting-club',
    name: 'ชมรมกีฬายิงปืน (Chula Shooting Club)',
    category: 'geela',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/logo_placeholder.png?alt=media',
  },
  {
    url: '/geela/chulalongkorn-futsal-team',
    name: 'ชมรมฟุตซอล',
    category: 'geela',
    logo: 'https://firebasestorage.googleapis.com/v0/b/club-mania2021.appspot.com/o/geela%2Fchulalongkorn-futsal-team%2Flogo1.png?alt=media',
  },
]
