// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    TextBody: typeof import('./src/components/typography/text-body1.vue')['default']
    TextBody1: typeof import('./src/components/typography/text-body1.vue')['default']
    TextBody2: typeof import('./src/components/typography/text-body2.vue')['default']
    TextCaption: typeof import('./src/components/typography/text-caption.vue')['default']
    TextLogo: typeof import('./src/components/typography/text-logo.vue')['default']
    TextOverline: typeof import('./src/components/typography/text-overline.vue')['default']
    TextSub1: typeof import('./src/components/typography/text-sub1.vue')['default']
    TextSub2: typeof import('./src/components/typography/text-sub2.vue')['default']
  }
}

export { }
