// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BackgroundSection: typeof import('./src/components/BackgroundSection.vue')['default']
    CarbonCloseFilled: typeof import('virtual:vite-icons/carbon/close-filled')['default']
    Filter: typeof import('./src/components/Filter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GeraCard: typeof import('./src/components/Card/Gera/gera-card.vue')['default']
    MdiAccountCircleOutline: typeof import('virtual:vite-icons/mdi/account-circle-outline')['default']
    MdiMagnify: typeof import('virtual:vite-icons/mdi/magnify')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    SlipvatCard: typeof import('./src/components/Card/SlipVat/slipvat-card.vue')['default']
    SlipvatImg: typeof import('./src/components/Card/SlipVat/slipvat-img.vue')['default']
    TextBody1: typeof import('./src/components/typography/text-body1.vue')['default']
    TextBody2: typeof import('./src/components/typography/text-body2.vue')['default']
    TextCaption: typeof import('./src/components/typography/text-caption.vue')['default']
    TextFrame: typeof import('./src/components/TextFrame.vue')['default']
    TextLogo: typeof import('./src/components/typography/text-logo.vue')['default']
    TextOverline: typeof import('./src/components/typography/text-overline.vue')['default']
    TextSub1: typeof import('./src/components/typography/text-sub1.vue')['default']
    TextSub2: typeof import('./src/components/typography/text-sub2.vue')['default']
    ToggleThing: typeof import('./src/components/ToggleThing.vue')['default']
    VichagarnCard: typeof import('./src/components/Card/Vichakarn/vichagarn-card.vue')['default']
    VichagarnTextCard: typeof import('./src/components/Card/Vichakarn/vichagarn-text-card.vue')['default']
    VichakarnImageCard: typeof import('./src/components/Card/Vichakarn/vichakarn-image-card.vue')['default']
  }
}

export { }
